# Generated by Django 4.1.3 on 2022-12-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0002_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupondiscount',
            field=models.IntegerField(null=True),
        ),
    ]
