# Generated by Django 4.1.3 on 2022-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0003_cartitem_coupondiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='guest',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
