# Generated by Django 4.1.3 on 2022-11-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='men_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price_s', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_l', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_xl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='women_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price_s', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_l', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_xl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
