# Generated by Django 4.1.3 on 2022-11-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ad',
        ),
        migrations.DeleteModel(
            name='men',
        ),
        migrations.DeleteModel(
            name='men_detail',
        ),
        migrations.DeleteModel(
            name='women',
        ),
        migrations.DeleteModel(
            name='women_detail',
        ),
    ]
