# Generated by Django 4.1.3 on 2022-11-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ads',
            new_name='ad',
        ),
        migrations.RenameModel(
            old_name='men_details',
            new_name='men_detail',
        ),
        migrations.RenameModel(
            old_name='women_details',
            new_name='women_detail',
        ),
    ]
