# Generated by Django 4.1.3 on 2022-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_ads_ad_rename_men_details_men_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='men_detail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='women_detail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
