# Generated by Django 4.1.3 on 2022-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_ad_picture_alter_men_detail_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='men_detail',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='women_detail',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
