# Generated by Django 4.1.3 on 2022-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_ad_picture_alter_men_detail_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='men_detail',
            name='catagory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='men_detail',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='women',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='women_detail',
            name='catagory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='women_detail',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
