# Generated by Django 4.1.3 on 2022-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_men_name_alter_men_detail_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='men_detail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='women_detail',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
