# Generated by Django 4.1.3 on 2022-11-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_ad_picture_alter_men_detail_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ad',
        ),
        migrations.DeleteModel(
            name='men',
        ),
        migrations.DeleteModel(
            name='men_detail',
        ),
        migrations.DeleteModel(
            name='women',
        ),
        migrations.DeleteModel(
            name='women_detail',
        ),
    ]
