# Generated by Django 4.1.3 on 2022-11-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
