# Generated by Django 4.1.3 on 2022-12-06 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_remove_profile_otp_account_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guest', max_length=200)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
