# Generated by Django 4.1.3 on 2022-12-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.guest'),
        ),
    ]
