# Generated by Django 4.1.3 on 2022-11-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagories',
            name='gender',
        ),
    ]
