# Generated by Django 4.1.3 on 2022-11-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0004_remove_catagories_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatagory_name', models.CharField(max_length=200)),
                ('catagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catagory.catagories')),
            ],
        ),
    ]
