# Generated by Django 4.1.3 on 2022-12-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0005_sub_catagories'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='hasoffer',
            field=models.BooleanField(default=False),
        ),
    ]
