# Generated by Django 4.1.3 on 2022-12-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0006_catagories_hasoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='offerrate',
            field=models.IntegerField(default=0),
        ),
    ]
