# Generated by Django 4.1.3 on 2022-12-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0007_catagories_offerrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagories',
            name='hasoffer',
        ),
        migrations.RemoveField(
            model_name='catagories',
            name='offerrate',
        ),
    ]
