# Generated by Django 4.1.3 on 2022-11-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reasoncancel',
            field=models.TextField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='reasonreturn',
            field=models.TextField(default='None', max_length=100),
        ),
    ]
