# Generated by Django 4.1.3 on 2022-12-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_address_guest'),
        ('orders', '0002_order_reasoncancel_order_reasonreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.guest'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.guest'),
        ),
        migrations.AddField(
            model_name='payment',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.guest'),
        ),
    ]
