# Generated by Django 4.1.3 on 2022-11-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
