# Generated by Django 4.1.3 on 2022-11-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_gender_products_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(default='MALE', max_length=200, unique=True),
        ),
    ]
