# Generated by Django 4.1.3 on 2022-11-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='gender',
        ),
    ]
