# Generated by Django 4.1.3 on 2022-11-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
