# Generated by Django 4.1.3 on 2022-11-17 06:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0005_sub_catagories'),
        ('products', '0013_alter_products_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_catagory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catagory.sub_catagories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='added_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 11, 23, 17896)),
        ),
    ]
