# Generated by Django 4.1.3 on 2022-11-17 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_sub_catagory_alter_products_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='added_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 13, 49, 233831)),
        ),
    ]
