# Generated by Django 4.1.3 on 2022-11-17 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_products_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sub_catagory',
        ),
        migrations.AlterField(
            model_name='products',
            name='added_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 14, 38, 726563)),
        ),
    ]
