# Generated by Django 4.1.3 on 2022-11-17 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_products_sub_catagory_alter_products_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='added_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 12, 34, 11, 548099)),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=10),
        ),
    ]
