# Generated by Django 4.1.3 on 2022-11-19 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_products_added_on_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='added_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 19, 12, 20, 40, 129193)),
        ),
    ]
