# Generated by Django 4.1.3 on 2022-11-24 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_products_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='products',
            name='sizeL',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='products',
            name='sizeM',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='products',
            name='sizeS',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='products',
            name='sizeXL',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='products',
            name='sizeXXL',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
