# Generated by Django 4.1.3 on 2022-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_products_size_products_sizel_products_sizem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default='S', max_length=200),
        ),
    ]
