# Generated by Django 4.1.3 on 2022-12-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
