# Generated by Django 4.1.3 on 2022-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_products_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discountprice',
            field=models.IntegerField(default=models.CharField(max_length=200, unique=True)),
        ),
    ]
