# Generated by Django 4.1.3 on 2022-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_products_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discountprice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
