# Generated by Django 4.1.3 on 2022-12-05 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_products_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discountprice',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
