# Generated by Django 4.1.3 on 2022-12-05 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_products_discountprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discountprice',
        ),
        migrations.AddField(
            model_name='products',
            name='disprice',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
