# Generated by Django 4.1.3 on 2022-12-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_products_discountprice_products_disprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='disprice',
        ),
        migrations.RemoveField(
            model_name='products',
            name='hasoffer',
        ),
    ]
