# Generated by Django 4.1.3 on 2022-12-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_products_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='hasoffer',
        ),
    ]
