# Generated by Django 4.1.3 on 2022-12-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0008_remove_catagories_hasoffer_and_more'),
        ('products', '0041_remove_products_discount_remove_products_hasoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagoryoffer',
            name='catagory',
        ),
        migrations.AddField(
            model_name='catagoryoffer',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='catagory.catagories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='products.products'),
        ),
    ]
